import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Frame from "./frame";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "KoLiBer",
    description: "Generated by create next app",
};

export default function Layout(props: {
    children: React.ReactNode;
    header: React.ReactNode;
    footer: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body dir="ltr" className={inter.className}>
                <Frame>
                    {props.header}
                    {props.children}
                    {props.footer}
                </Frame>
            </body>
        </html>
    );
}
